// Generated by CoffeeScript 1.8.0
(function() {
  var History;

  History = require('../src/history');

  module.exports = {
    simpleTest: function(test) {
      var h, i, o, p, t, _i, _j, _k;
      o = {
        v: [1]
      };
      t = function(_arg) {
        var v;
        v = _arg.v;
        return {
          v: v,
          t: true
        };
      };
      h = new History(o, 2, t);
      o.v[0] = 1;
      h.snapshot();
      o.v[0] = 2;
      h.snapshot();
      o.v[0] = 3;
      h.snapshot();
      o.v[0] = 4;
      h.snapshot();
      test.equal(o.v[0], 4);
      test.ok(o.t == null);
      for (i = _i = 0; _i >= -3; i = --_i) {
        p = h.past(i);
        test.strictEqual(p.t, true);
        test.equal(p.v[0], 4 + i);
      }
      o.v[0] = 5;
      h.snapshot();
      o.v[0] = 6;
      h.snapshot();
      test.equal(o.v[0], 6);
      test.ok(o.t == null);
      for (i = _j = 0; _j >= -3; i = --_j) {
        p = h.past(i);
        test.strictEqual(p.t, true);
        test.equal(p.v[0], 6 + i);
      }
      o.v[0] = 7;
      h.snapshot();
      o.v[0] = 8;
      h.snapshot();
      test.equal(o.v[0], 8);
      test.ok(o.t == null);
      for (i = _k = 0; _k >= -3; i = --_k) {
        p = h.past(i);
        test.strictEqual(p.t, true);
        test.equal(p.v[0], 8 + i);
      }
      return test.done();
    }
  };

}).call(this);

//# sourceMappingURL=history.test.js.map
