// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = {
    World: require('./src/world'),
    Force: require('./src/force'),
    Body: require('./src/body'),
    SE2: require('./src/se2'),
    Solver: require('./src/solver')
  };

}).call(this);

//# sourceMappingURL=index.js.map
